[project]
name = "dragonocr"
version = "0.1.0"
description = "OCR for Dragon"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openpyxl",
    "pillow",
    "pyinstaller>=6.12.0",
    "pytesseract",
]
